# Each [[run]] corresponds to either pintool or trace process.

[[run]]
type = "trace"
num_instrs_to_skip_first = 0
trace_file = "/tmp/test.0.snappy"
path = "/home/gajh/repository/mcsim_private/Pthread/obj-intel64"
arg  = "bin.exe"

