# Each [[run]] corresponds to either pintool or trace process.

[[run]]
type = "trace"
num_instrs_to_skip_first = 0
trace_file = "/tmp/stream.0.snappy"
path = "/home/gajh/repository/mcsim_private/McSim/stream"
arg  = "STREAM"
