# Each [[run]] corresponds to either pintool or trace process.

[[run]]
type = "trace"
num_instrs_to_skip_first = 0
trace_file = "/scale/cal/share/research/benchmarks/spec-cpu2017-snappy-modernize/554.21190.snappy"
path = "/scale/cal/home/wjdoh/mcsim_private/McSim/dummy"
arg  = "hello"

[[run]]
type = "trace"
num_instrs_to_skip_first = 0
trace_file = "/scale/cal/share/research/benchmarks/spec-cpu2017-snappy-modernize/523.1214.snappy"
path = "/scale/cal/home/wjdoh/mcsim_private/McSim/dummy"
arg  = "hello"


[[run]]
type = "trace"
num_instrs_to_skip_first = 0
trace_file = "/scale/cal/share/research/benchmarks/spec-cpu2017-snappy-modernize/520.6293.snappy"
path = "/scale/cal/home/wjdoh/mcsim_private/McSim/dummy"
arg  = "hello"


[[run]]
type = "trace"
num_instrs_to_skip_first = 0
trace_file = "/scale/cal/share/research/benchmarks/spec-cpu2017-snappy-modernize/520.3162.snappy"
path = "/scale/cal/home/wjdoh/mcsim_private/McSim/dummy"
arg  = "hello"

